name: "release"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: "build"
    runs-on: "windows-2022"

    steps:
      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: make zip

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          make.exe genzip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            VRChatRejoinTool.zip

